# Generated by Django 3.1.2 on 2020-11-28 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='feedback',
            new_name='product_feedback',
        ),
    ]
